### PR TITLE
Cinder: Add support for os-terminate_connection

### PR DESCRIPTION
**Pull request by rollandf**
V3.1.x

### CODE REVIEW

**Comment by rollandf** [comment]
@simon3z CI is failing due to missing dependencies:
[ERROR] Failed to execute goal on project openstack-examples: Could not resolve dependencies for project com.woorea:openstack-examples:jar:3.1.3-SNAPSHOT: Could not find artifact com.woorea:jersey2-connector:jar:3.1.2-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by rollandf** [comment]
@danielerez please review

**Comment by rollandf** [comment]
ping

**Comment by danielerez** [comment]
+1 looks good.

**Comment by rollandf** [comment]
Thanks!!

**Pull request merged**
