### PR TITLE
Cinder: Add support for os-terminate_connection

### PR DESCRIPTION
**Pull request by rollandf**
See : 
**https://github.com/openstack/cinder/blob/master/cinder/api/contrib/volume_actions.py#L202**

### CODE REVIEW

**Comment by rollandf** [comment]
@danielerez please review

**Comment by danielerez** [comment]
Looks good.

**Comment by rollandf** [comment]
@simon3z Can you please review ?

**Comment by simon3z** [comment]
@rollandf I suppose you want to backport this to `v3.1.x`, right?

**Comment by rollandf** [comment]
Yes, I will send a new PR for v3.1.x

**Pull request merged**
